# Generated by Django 3.1.1 on 2020-09-12 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('questionnaire_id', models.IntegerField()),
                ('question_id', models.IntegerField()),
                ('answerer_name', models.CharField(max_length=64)),
                ('answerer_ip', models.CharField(max_length=64)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AnswerDetail',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('questionnaire_id', models.IntegerField()),
                ('answer_id', models.IntegerField()),
                ('question_id', models.IntegerField()),
                ('answer', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('questionnaire_id', models.IntegerField()),
                ('question_id', models.IntegerField()),
                ('number', models.IntegerField()),
                ('text', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('questionnaire_id', models.IntegerField()),
                ('question', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=64)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('create_user_id', models.IntegerField()),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_user_id', models.IntegerField()),
                ('update_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
